# Generated by Django 5.2.7 on 2025-10-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Description',
            new_name='description',
        ),
    ]
