# Generated by Django 5.2.7 on 2025-11-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='shg_group',
            new_name='shg_group_id',
        ),
    ]
