# Generated by Django 5.2.7 on 2025-10-26 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
        ('Products', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='shg_group_registration',
            old_name='Address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='shg_group_registration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shg_group_registration',
            name='date_of_formation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shg_group_registration',
            name='district',
            field=models.CharField(choices=[('NORTH_GOA', 'North Goa'), ('SOUTH_GOA', 'South Goa')], default='NORTH_GOA', max_length=20),
        ),
        migrations.AlterField(
            model_name='shg_group_registration',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shg_group_registration',
            name='type_of_shg',
            field=models.CharField(choices=[('WOMEN', 'Women'), ('MEN', 'Men'), ('MIXED', 'Mixed')], default='WOMEN', max_length=10),
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time_of_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customer_orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
                ('shg_groups_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.shg_group_registration')),
            ],
        ),
    ]
