# Generated by Django 5.2.7 on 2025-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_address_shg_group_registration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shg_group_registration',
            name='registration_number',
            field=models.CharField(max_length=20),
        ),
    ]
