# Generated by Django 5.2.7 on 2025-10-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_shg_group_registration_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shg_group_registration',
            old_name='name_of_sng',
            new_name='name_of_shg',
        ),
        migrations.AlterField(
            model_name='shg_group_registration',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
