# Generated by Django 5.2.7 on 2025-10-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_order_items_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shg_group_registration',
            old_name='user',
            new_name='shg',
        ),
    ]
