# Generated by Django 5.2.7 on 2025-11-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_rename_user_shg_group_registration_shg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shg_group_registration',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shg_group_registration',
            name='district',
            field=models.CharField(choices=[('North Goa', 'North Goa'), ('South Goa', 'South Goa')], default='North Goa', max_length=20),
        ),
        migrations.AlterField(
            model_name='shg_group_registration',
            name='type_of_shg',
            field=models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Mixed', 'Mixed')], default='Women', max_length=10),
        ),
    ]
