# Generated by Django 5.2.7 on 2025-10-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_remove_customerform_password_customerform_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerform',
            name='email',
        ),
    ]
